name: Artifacts
on:
  pull_request:
    paths:
      - '.github/workflows/artifacts.yaml'
      - 'tools/buildimage/**'
  push:
    branches:
      - main
jobs:
  export-docker-image-arm64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Docker Buildx for multi-platform builds
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Install Bazel dependencies
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y curl gnupg2 apt-transport-https ca-certificates software-properties-common

    - name: Install Bazel
      run: sudo bash tools/buildutils/installbazel.sh

    - name: Bazel version
      run: bazel version

    # Build docker image using Buildx
    - name: Build docker image with Buildx
      run: |
        ./docker/image-build-bazel-wrapper.sh

    # Upload Docker image as artifact
    - name: Publish docker image
      uses: actions/upload-artifact@v4
      with:
        name: docker-image-arm64
        path: orchestration-image-arm64-${{ github.sha }}.tar
