name: Artifacts
on:
  pull_request:
    paths:
      - '.github/workflows/artifacts.yaml'
      - 'tools/buildimage/**'
  push:
    branches:
      - main
jobs:
  export-docker-image-arm64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Get docker image name
      run: |
        short_sha=$(echo ${{ github.sha }} | cut -c1-8)
        echo "arm64_image_path=orchestration-image-arm64-${short_sha}.tar" >> $GITHUB_ENV

    - name: Install bazel
      run: sudo bash tools/buildutils/installbazel.sh

    - name: Build and save Docker image
      run: |
        # Build the Docker image for arm64 architecture
        docker buildx build --platform linux/arm64 -t orchestration-image-arm64 --output type=docker,dest=${{ env.arm64_image_path }} .

    - name: Publish docker image
      uses: actions/upload-artifact@v4
      with:
        name: docker-image-arm64
        path: ${{ env.arm64_image_path }}
